
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '50920C81895ED09E6ACBEA647DD1D091'
    
_lr_action_items = {'NOT':([2,],[4,]),'PREDICATE':([0,2,4,7,8,9,],[1,1,1,1,1,1,]),'OR':([1,5,10,14,15,16,],[-5,7,-1,-3,-4,-2,]),'RPAREN':([1,6,10,11,12,13,14,15,16,],[-5,10,-1,14,15,16,-3,-4,-2,]),'IMPLIES':([1,5,10,14,15,16,],[-5,8,-1,-3,-4,-2,]),'AND':([1,5,10,14,15,16,],[-5,9,-1,-3,-4,-2,]),'$end':([1,3,10,14,15,16,],[-5,0,-1,-3,-4,-2,]),'LPAREN':([0,2,4,7,8,9,],[2,2,2,2,2,2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pred':([0,2,4,7,8,9,],[3,5,6,11,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pred","S'",1,None,None,None),
  ('pred -> LPAREN NOT pred RPAREN','pred',4,'p_NOT','lex.py',20),
  ('pred -> LPAREN pred AND pred RPAREN','pred',5,'p_exp','lex.py',26),
  ('pred -> LPAREN pred OR pred RPAREN','pred',5,'p_exp','lex.py',27),
  ('pred -> LPAREN pred IMPLIES pred RPAREN','pred',5,'p_exp','lex.py',28),
  ('pred -> PREDICATE','pred',1,'p_terminal','lex.py',34),
]
